name: iOS Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      track:
        description: 'Release track'
        required: true
        default: 'testflight-dev'
        type: choice
        options:
          - testflight-dev
          - testflight-staging
          - testflight-prod
          - firebase

env:
  FLUTTER_VERSION: "3.32.8"
  FLUTTER_CHANNEL: "stable"

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: ios

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_DEPLOY_KEY }}

      - name: Setup Service Accounts
        env:
          CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        run: |
          cat <<< "$CREDENTIAL_FILE_CONTENT" > service_credentials_content.json

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Release to TestFlight (Dev)
        if: ${{ github.event_name == 'push' || github.event.inputs.track == 'testflight-dev' }}
        working-directory: ios
        run: bundle exec fastlane release_testflight_dev
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8_BASE64: ${{ secrets.ASC_KEY_P8_BASE64 }}

      - name: Release to TestFlight (Staging)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.track == 'testflight-staging' }}
        working-directory: ios
        run: bundle exec fastlane release_testflight_staging
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8_BASE64: ${{ secrets.ASC_KEY_P8_BASE64 }}

      - name: Release to TestFlight (Prod)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.track == 'testflight-prod' }}
        working-directory: ios
        run: bundle exec fastlane release_app_store
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8_BASE64: ${{ secrets.ASC_KEY_P8_BASE64 }}
          APP_BUNDLE_ID: ${{ vars.APP_BUNDLE_ID }}

      - name: Release to Firebase (iOS Dev)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.track == 'firebase' }}
        working-directory: ios
        run: bundle exec fastlane release_firebase
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8_BASE64: ${{ secrets.ASC_KEY_P8_BASE64 }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_APP_ID_IOS_DEV: ${{ secrets.FIREBASE_APP_ID_IOS_DEV }}
